services:
  martin:
    env_file:
      - .env
    build: ./martin
    restart: unless-stopped
    ports:
      - "3333:3000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@martin-db/${POSTGRES_DB}
    volumes:
      - ./martin/mbtiles:/martin/mbtiles
    depends_on:
      - martin-db
  martin-db:
    env_file:
      - .env
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/pg_data:/var/lib/postgresql/data
  nginx:
    build: ../frontend
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - martin
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../scripts/live_results:/www/data/results:ro
  scrape_results:
    profiles:
      - scrape
    build:
      context: ..
      dockerfile: ./docker/scrape_results/Dockerfile
    restart: unless-stopped
    shm_size: 1gb
    init: true
    volumes:
      - ../scripts/live_results:/app/live_results
      - ../scripts/data_in:/app/data_in
      - ../scripts/data_processed:/app/data_processed:ro
  mock_results:
    profiles:
      - mock
    build:
      context: ..
      dockerfile: ./docker/mock_results/Dockerfile
    volumes:
      - ../scripts/live_results:/app/live_results
      - ../scripts/data_in:/app/data_in
      - ../scripts/data_processed:/app/data_processed:ro
